/**
 * Chronexa main entry — replaces build_bundle.sh + the index.html script list.
 *
 * Import order below IS the canonical module load order (same as the old
 * bundle manifest); many modules register into shared namespaces at eval
 * time, so do not re-sort. CSS import order mirrors the old <link> order —
 * later files intentionally override earlier ones. css/tokens.css owns the
 * --chrx-* namespace as the single source of truth; theme-specific styling
 * layers on top.
 */

import "@astryxdesign/core/reset.css";
import "@astryxdesign/core/astryx.css";
import "../../css/chronexa-theme.css";

import "../../css/tokens.css";
import "../../css/tailwind.css";
import "../../css/style.css";
import "../../css/components.css";
import "../../css/solver_ui.css";
import "../../css/ribbon.css";
import "../../css/entities.css";
import "../../css/editor.css";
import "../../css/drag_ux.css";
import "../../css/teacher_colors.css";
import "../../css/substitution.css";
import "../../css/motion.css";
import "../../css/design-v3.css";
import "../../css/first-five-minutes.css";
// Landing redesign stylesheet — replaces landing-pixels.css + landing-anim.css
// (both retired 2026-08-02; files kept on disk for the lessons page).
import "../../css/landing-redesign.css";
// Editor v3 "Studio" — system-native surface for the whole editor page.
// Loaded LAST so it resolves over editor.css / drag_ux.css / design-v3.css.
import "../../css/editor-v3.css";

import "../ui/state.js";
import "../ui/components/icons.js";
import "../ui/i18n.js";
import "../xml/parse_timetable_xml.js";
import "../ui/grid_view.js";
import "../ui/school_info.js";
import "../ui/class_grid.js";
import "../ui/teacher_grid.js";
import "../ui/room_grid.js";
import "../ui/inspector.js";
import "../ui/components/help_tooltip.js";
import "../ui/components/landing_demo.js";
import "../ui/components/first_card_coachmark.js";
import "../ui/entities/dialog_shell.js";
import "../ui/components/bell_resolver.js";
import "../ui/components/time_off_matrix.js";
import "../ui/components/class_constraints_dialog.js";
import "../ui/components/teacher_constraints_dialog.js";
import "../ui/components/divisions_tree.js";
import "../ui/entities/subjects.js";
import "../ui/entities/classes.js";
import "../ui/entities/classrooms.js";
import "../ui/entities/teachers.js";
import "../ui/entities/lessons.js";
import "../ui/entities/relations.js";
import "../ui/entities/bells.js";
import "../ui/entities/breaks.js";
import "../ui/entities/classroomsupervisions.js";
import "../ui/entities/coursegroups.js";
import "../ui/entities/buildings.js";
import "../ui/entities/divisions.js";
import "../ui/entities/groups.js";
import "../ui/entities/days.js";
import "../ui/entities/terms.js";
import "../ui/entities/weeks.js";
import "../ui/entities/ttreports.js";
import "../ui/entities/ttviews.js";
import "../ui/entities/grades.js";
import "../ui/entities/holidays.js";
import "../ui/entity_router.js";
import "../ui/multi_doc_tabs.js";
import "../ui/shell_v3.js";
import "../ui/components/statistics_panel.js";
import "../ui/components/school_settings_dialog.js";
import "../ui/components/solver_parameters_dialog.js";
import "../ui/components/supervision_criteria_dialog.js";
import "../ui/components/tag_caps_dialog.js";
import "../ui/entities/students.js";
import "../ui/entities/studentsubjects.js";
import "../ui/components/school_hub.js";
import "../ui/components/school_toolbar.js";
import "../ui/components/period_override_matrix.js";
import "../ui/components/ai_actions.js";
import "../ui/io/export_html.js";
import "../ui/components/verification.js";
import "../ui/solver_ui/backend_client.js";
import "../ui/solver_ui/multi_branch.js";
import "../ui/solver_ui/prelaunch_dialog.js";
import "../ui/solver_ui/progress_modal.js";
import "../ui/solver_ui/result_panel.js";
import "../ui/solver_ui/verification_panel.js";
import "../ui/solver_ui/test_dialog.js";
import "../ui/wizard/create_new.js";
import "../ui/wizard/wizard_walkthrough.js";
import "../ui/editor/activator.js";
import "../ui/pwa_install.js";
import "../ui/editor/grid_canvas.js";
import "../ui/editor/canvas_geometry.js";
import "../ui/editor/pending_strip.js";
import "../ui/editor/placement_validator.js";
import "../ui/editor/card_in_hand.js";
import "../ui/editor/row_context_menu.js";
import "../ui/editor/empty_cell_context.js";
import "../ui/editor/header_context.js";
import "../ui/editor/card_double_click.js";
import "../ui/editor/card_context_menu.js";
import "../ui/editor/constraint_explainer.js";
import "../ui/start_screen.js";
import "../ui/main.js";
import "../ui/onboarding/data_library.js";
import "../ui/onboarding/school_templates.js";
import "../ui/onboarding/bulk_add_wizard.js";
import "../ui/onboarding/tour.js";
import "../ui/onboarding/smart_defaults.js";
import "../ui/onboarding/wiring.js";
import "../ui/ribbon/topbar.js";
import "../ui/ribbon/undo_redo.js";
import "../ui/ribbon/menus/main_menu.js";
import "../ui/ribbon/menus/files_menu.js";
import "../ui/ribbon/menus/specification_menu.js";
import "../ui/ribbon/menus/view_menu.js";
import "../ui/ribbon/menus/timetable_menu.js";
import "../ui/ribbon/menus/options_menu.js";
import "../ui/ribbon/menus/help_menu.js";
import "../ui/ribbon/menus/ai_menu.js";
import "../ui/io/import_timetable_xml.js";
import "../ui/io/export_timetable_xml.js";
import "../ui/io/export_excel.js";
import "../ui/io/snapshot.js";
import "../ui/io/import_basic_xml.js";
import "../ui/io/import_bell_times.js";
import "../ui/io/import_clipboard.js";
import "../ui/io/import_gp_untis.js";
import "../ui/io/export_legacy_roz.js";
import "../ui/io/export_gp_untis_dif.js";
import "../ui/io/export_atlantis.js";
import "../ui/io/export_powerschool.js";
import "../ui/io/export_excel_class_register.js";
import "../ui/io/export_excel_nyc.js";
import "../ui/io/export_ics.js";
import "../ui/print_preview/cell_style_dialog.js";
import "../ui/print_preview/print_settings_dialog.js";
import "../ui/print_preview/templates_registry.js";
import "../ui/print_preview/templates/_helpers.js";
import "../ui/print_preview/print_report_schema.js";
import "../ui/print_preview/pivot_cell_renderer.js";
import "../ui/print_preview/pivot_engine.js";
import "../ui/print_preview/modify_structure_dialog.js";
import "../ui/print_preview/filter_dialog.js";
import "../ui/print_preview/extras_dialog.js";
import "../ui/print_preview/sizes_design_colors_dialogs.js";
import "../ui/print_preview/header_dialog.js";
import "../ui/print_preview/templates/timetable_for_student.js";
import "../ui/print_preview/templates/timetable_for_each_student.js";
import "../ui/print_preview/templates/summary_of_students.js";
import "../ui/print_preview/templates/summary_of_subjects.js";
import "../ui/print_preview/templates/wall_poster_classrooms.js";
import "../ui/print_preview/templates/lesson_grid.js";
import "../ui/print_preview/templates/classwise_with_table.js";
import "../ui/print_preview/templates/teacherwise_with_table.js";
import "../ui/print_preview/templates/teacherwise_extra.js";
import "../ui/print_preview/templates/contract_overview.js";
import "../ui/print_preview/templates/daily_attendance.js";
import "../ui/print_preview/templates/timetable_for_each_subject.js";
import "../ui/print_preview/templates/summary_of_teachers.js";
import "../ui/print_preview/templates/summary_of_classrooms.js";
import "../ui/print_preview/templates/wall_poster_teachers.js";
import "../ui/print_preview/templates/list_of_teachers.js";
import "../ui/print_preview/templates/list_of_classes.js";
import "../ui/print_preview/templates/custom_slots.js";
import "../ui/print_preview/print_presets.js";
import "../ui/io/compare_files.js";
import "../ui/io/import_cardrelationships_har.js";
import "../ui/io/snapshots.js";
import "../ui/components/lessons_grid_matrix.js";
import "../ui/components/approbation_matrix.js";
import "../ui/components/verification_panel_pro.js";
import "../ui/components/color_taxonomy.js";
import "../ui/components/master_solver_wizard.js";
import "../ui/components/dashboards.js";
import "../ui/components/constraints_library.js";
import "../ui/components/help_center.js";
import "../ui/components/auto_save.js";
import "../ui/components/solver_presets.js";
import "../ui/components/per_day_bell_override.js";
import "../ui/components/entity_field_gaps.js";
import "../ui/components/advisor.js";
import "../solver/improve_mode.js";
import "../solver/score_expr.js";
import "../ui/print_preview/print_preview.js";
import "../ui/ribbon/bootstrap.js";
import "../ui/substitution/main.js";
import "../ui/substitution/candidate_ranker.js";
import "../ui/substitution/absence_input.js";
import "../ui/substitution/classwise_output.js";
import "../ui/substitution/teacherwise_output.js";
import "../ui/substitution/print_memo.js";
import "../ui/editor/focus_mode.js";
import "../ui/components/command_palette.js";

// Solver shims for the main thread (was an inline <script type="module">
// in index.html). Dynamic imports keep the solver graph in its own chunk.
import "./solver_shims.js";
