// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "../state.js";
import "./backend_client.js";

/* Chronexa Solver — Pre-launch dialog (Generate flow redesign).
 *
 * Moment 1 of 3 in the unified Generate flow: ASK.
 *   Ask (this dialog) → Work (progress_modal.js) → Land (result_panel.js)
 *
 * Redesign principles:
 *   - Preset-first: Fast preview / Balanced / Best result / Custom. The old
 *     Complexity + Conditions + Algorithm radios still exist with the same
 *     input names, but live inside a collapsed "Advanced" section — Custom
 *     reveals them. School size auto-picks the preset.
 *   - One language: titles/counts use "placed / left to place" everywhere so
 *     Ask, Work and Land read as one flow.
 *   - Class-name contract (do not rename — e2e + solver_presets observer):
 *       .csu-modebtn[data-mode] + .is-selected, .chrx-preset-card,
 *       #csu-prelaunch-start, #csu-prelaunch-summary,
 *       input names complexity/conditions/algorithm.
 *
 * Public API (unchanged):
 *   SolverUI.PreLaunch.open(opts)
 *     opts.defaultMode : "generate" | "test" | "improve" | "best" (default "best")
 *     opts.school      : SchoolData (only used for the summary strip)
 *     opts.onConfirm(cfg), opts.onCancel()
 *   cfg = { mode, complexity, conditions, algorithm, showReport,
 *           timeLimitSec, warmStart?, useLNS?, improve? }
 */
(function (global) {
  "use strict";

  const TIME_LIMIT_BY_COMPLEXITY = { normal: 30, large: 60, huge: 120 };

  // Preset → underlying solver knobs. Conditions values must match the
  // Advanced radio values (draft / relax / strict).
  const PRESETS = [
    { id: "fast",     label: "Fast preview", sub: "30s · quick check",        timeLimitSec: 30,  complexity: "normal", conditions: "draft",  icon: "◷" },
    { id: "balanced", label: "Balanced",     sub: "90s · recommended",        timeLimitSec: 90,  complexity: "large",  conditions: "relax",  icon: "⚖", recommended: true },
    { id: "best",     label: "Best result",  sub: "5 min · final timetable",  timeLimitSec: 300, complexity: "huge",   conditions: "strict", icon: "★" },
    { id: "custom",   label: "Custom",       sub: "Tune everything",          custom: true, icon: "⚙" },
  ];
  const PRESET_BY_COMPLEXITY = { normal: "fast", large: "balanced", huge: "best" };

  let host, dialog, current;

  function el(tag, attrs, ...kids) {
    const n = document.createElement(tag);
    if (attrs) for (const k in attrs) {
      if (k === "class") n.className = attrs[k];
      else if (k.startsWith("on") && typeof attrs[k] === "function") n.addEventListener(k.slice(2), attrs[k]);
      else n.setAttribute(k, attrs[k]);
    }
    for (const c of kids) if (c != null) n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    return n;
  }

  function radioGroup(name, options, defaultValue) {
    const wrap = el("div", { class: "csu-radio-row", role: "radiogroup", "aria-label": name });
    for (const o of options) {
      const id = `csu-${name}-${o.value}`;
      const input = el("input", { type: "radio", name, id, value: o.value });
      if (o.value === defaultValue) input.checked = true;
      const lab = el("label", { class: "csu-radio", for: id },
        input,
        el("span", { class: "csu-radio__title" }, o.label),
        o.hint ? el("span", { class: "csu-radio__hint" }, o.hint) : null,
      );
      wrap.appendChild(lab);
    }
    return wrap;
  }

  function selectedRadio(wrap, name) {
    const r = wrap.querySelector(`input[name="${name}"]:checked`);
    return r ? r.value : null;
  }

  function modeButton(mode, icon, title, hint) {
    return el("button", {
      type: "button",
      class: "csu-modebtn",
      "data-mode": mode,
      onclick: () => setMode(mode),
    },
      el("span", { class: "csu-modebtn__icon" }, icon),
      el("span", { class: "csu-modebtn__title" }, title),
      el("span", { class: "csu-modebtn__hint" }, hint),
    );
  }

  function build() {
    host = el("div", { class: "csu-backdrop", role: "presentation", "aria-hidden": "true" });
    host.addEventListener("click", (e) => { if (e.target === host) doCancel(); });

    dialog = el("section", {
      class: "csu-dialog csu-prelaunch",
      role: "dialog",
      "aria-modal": "true",
      "aria-labelledby": "csu-prelaunch-title",
    });

    const titleEl = el("h2", { class: "csu-dialog__title", id: "csu-prelaunch-title" }, "Generate timetable");
    const sub = el("p", { class: "csu-dialog__sub" }, "One click builds the whole week. Pick a speed — the details stay automatic.");
    const summary = el("div", { class: "csu-dialog__summary", id: "csu-prelaunch-summary" }, "");

    // --- Mode: Best first (default), Test demoted to a quiet secondary ----
    const modeBtnBest = modeButton("best", "★", "Best timetable", "Draft fast, then polish — one click, offline, toward 100%.");
    const modeBtnGen = modeButton("generate", "✦", "Generate timetable", "Run the solver from scratch and place cards.");
    const modeBtnImp = modeButton("improve", "⚡", "Improve current schedule", "Keep placements; search outward for improvements.");
    const modeBtnTest = modeButton("test", "✓", "Test the timetable", "Validate constraints — does not move any card.");
    modeBtnTest.classList.add("csu-modebtn--quiet");
    const modeRow = el("div", { class: "csu-mode-row" }, modeBtnBest, modeBtnGen, modeBtnImp, modeBtnTest);

    // --- Preset picker (native; same class names the old observer injected
    // so e2e locators and the observer guard keep working) ------------------
    const presetGrid = el("div", { class: "chrx-preset-grid", role: "radiogroup", "aria-label": "Speed" });
    for (const p of PRESETS) {
      const card = el("button", {
        type: "button",
        class: "chrx-preset-card" + (p.recommended ? " chrx-preset-card--recommended" : ""),
        "data-preset": p.id,
        role: "radio",
        "aria-checked": p.id === "balanced" ? "true" : "false",
        onclick: () => selectPreset(p.id),
      },
        el("div", { class: "chrx-preset-label" }, (p.icon ? p.icon + " " : "") + p.label),
        el("div", { class: "chrx-preset-sub" }, p.sub),
      );
      if (p.recommended) card.appendChild(el("span", { class: "chrx-preset-badge" }, "Recommended"));
      presetGrid.appendChild(card);
    }
    const presetStrip = el("div", { class: "chrx-preset-strip", "data-native": "true" },
      el("p", { class: "chrx-preset-title" }, "Speed"),
      presetGrid,
    );

    // --- Advanced (collapsed): the old Complexity / Conditions / Algorithm --
    const complexity = radioGroup("complexity", [
      { value: "normal", label: "Normal", hint: "30s · small school" },
      { value: "large",  label: "Large",  hint: "60s · 30–50 classes" },
      { value: "huge",   label: "Huge",   hint: "2 min · 60+ teachers" },
    ], "large");
    const conditions = radioGroup("conditions", [
      { value: "draft",  label: "Draft",             hint: "Accept any partial result." },
      { value: "relax",  label: "Allow relaxation",  hint: "Skip the toughest soft constraints if stuck." },
      { value: "strict", label: "Strict",            hint: "Reject anything with hard conflicts." },
    ], "relax");
    const cloudReady = !!(global.CHRONEXA_BACKEND_URL && global.CHRONEXA_BACKEND_URL.length > 0);
    const algorithm = radioGroup("algorithm", [
      { value: "browser", label: "Run on this computer", hint: "Uses a Web Worker. Stays offline." },
      { value: "wasm",    label: "CP-SAT in browser",    hint: "Full OR-Tools portfolio · offline · multi-threaded." },
      { value: "cloud",   label: "Run on cloud",          hint: cloudReady ? "OR-Tools CP-SAT via backend." : "Backend URL not set — will fall back to browser." },
    ], "browser");
    const advanced = el("details", { class: "csu-advanced", id: "csu-advanced" },
      el("summary", { class: "csu-advanced__toggle" }, "Advanced — complexity, conditions, algorithm"),
      el("div", { class: "csu-advanced__body" },
        sectionTitle("Complexity"),    complexity,
        sectionTitle("Conditions"),    conditions,
        el("div", { id: "csu-algo-section" }, sectionTitle("Algorithm"), algorithm),
      ),
    );

    // --- Report toggle -------------------------------------------------------
    const reportTog = el("input", { type: "checkbox", id: "csu-show-report" });
    reportTog.checked = true;
    const reportLabel = el("label", { class: "csu-toggle", for: "csu-show-report" },
      reportTog,
      el("span", null, "Show solver report after run"),
    );

    // --- Actions -------------------------------------------------------------
    const cancelBtn = el("button", { type: "button", class: "chrx-btn csu-btn--ghost", onclick: doCancel }, "Cancel");
    const startBtn  = el("button", { type: "button", class: "chrx-btn chrx-btn--primary", id: "csu-prelaunch-start", onclick: doStart }, "Build best timetable");
    const footNote = el("p", { class: "csu-dialog__foot" }, "Offline by default · cloud only if you pick it.");
    const actions = el("div", { class: "csu-dialog__actions" }, cancelBtn, startBtn);

    dialog.append(titleEl, sub, summary, modeRow, presetStrip, advanced, reportLabel, actions, footNote);
    dialog.dataset.preset = "balanced";
    host.appendChild(dialog);
    document.body.appendChild(host);

    host.addEventListener("keydown", (e) => {
      if (e.key === "Escape") { e.preventDefault(); doCancel(); }
    });
  }

  function sectionTitle(text) {
    return el("h3", { class: "csu-dialog__section" }, text);
  }

  function selectPreset(id) {
    if (!dialog) return;
    const preset = PRESETS.find(p => p.id === id) || PRESETS[1];
    dialog.dataset.preset = preset.id;
    if (preset.timeLimitSec) dialog.dataset.timeLimitSec = String(preset.timeLimitSec);
    else delete dialog.dataset.timeLimitSec;
    dialog.querySelectorAll(".chrx-preset-card").forEach(c => {
      const on = c.dataset.preset === preset.id;
      c.classList.toggle("is-selected", on);
      c.setAttribute("aria-checked", on ? "true" : "false");
    });
    if (!preset.custom) {
      const radios = dialog.querySelectorAll('input[type="radio"]');
      radios.forEach(r => {
        if (r.name === "complexity" && r.value === preset.complexity) r.checked = true;
        if (r.name === "conditions" && r.value === preset.conditions) r.checked = true;
      });
      dialog.querySelector("#csu-advanced").open = false;
    } else {
      dialog.querySelector("#csu-advanced").open = true;
    }
  }

  function setMode(mode) {
    if (!dialog) return;
    dialog.querySelectorAll(".csu-modebtn").forEach(b => {
      b.classList.toggle("is-selected", b.dataset.mode === mode);
    });
    const startBtn = dialog.querySelector("#csu-prelaunch-start");
    if (startBtn) startBtn.textContent =
      mode === "test" ? "Run test" :
      mode === "best" ? "Build best timetable" :
      mode === "improve" ? "Improve" : "Start generation";
    // Algorithm/backend choice only applies to Generate and Improve.
    const algoSec = dialog.querySelector("#csu-algo-section");
    if (algoSec) algoSec.style.display = (mode === "generate" || mode === "improve") ? "" : "none";
    // Test is validate-only: speed presets don't apply.
    const strip = dialog.querySelector(".chrx-preset-strip");
    if (strip) strip.style.display = mode === "test" ? "none" : "";
    dialog.dataset.mode = mode;
  }

  function setSummary(school) {
    const sum = dialog.querySelector("#csu-prelaunch-summary");
    if (!sum) return;
    if (!school) { sum.textContent = ""; sum.classList.remove("is-on"); return; }
    const c = (school._meta && school._meta.counts) || {};
    const teachers = (school.teachers && school.teachers.length) || c.teachers || 0;
    const classes  = (school.classes  && school.classes.length)  || c.classes  || 0;
    const lessons  = (school.lessons  && school.lessons.length)  || c.lessons  || 0;
    const cards    = (school.cards    && school.cards.length)    || c.cards    || 0;
    sum.innerHTML = "";
    const chip = (n, label) => {
      const s = el("span", { class: "csu-chip" },
        el("strong", {}, String(n)), document.createTextNode(" " + label));
      sum.appendChild(s);
    };
    const name = el("span", { class: "csu-chip csu-chip--name" }, school.schoolName || "(school)");
    sum.appendChild(name);
    chip(teachers, "teachers");
    chip(classes, "classes");
    chip(lessons, "lessons");
    chip(cards, "placed");
    sum.classList.add("is-on");
  }

  function doCancel() {
    close();
    if (current && current.onCancel) {
      try { current.onCancel(); } catch (e) { console.error(e); }
    }
    current = null;
  }

  function doStart() {
    const mode = dialog.dataset.mode || "best";
    const preset = PRESETS.find(p => p.id === dialog.dataset.preset);
    const cfg = {
      mode,
      complexity: selectedRadio(dialog, "complexity") || "large",
      conditions: selectedRadio(dialog, "conditions") || "relax",
      algorithm:  selectedRadio(dialog, "algorithm")  || "browser",
      showReport: !!dialog.querySelector("#csu-show-report").checked,
    };
    // Preset time wins; Custom (or no preset) falls back to complexity tiers.
    cfg.timeLimitSec = (preset && preset.timeLimitSec)
      || Number(dialog.dataset.timeLimitSec)
      || TIME_LIMIT_BY_COMPLEXITY[cfg.complexity]
      || 60;
    if (mode === "best") cfg.algorithm = "auto";
    if (mode === "improve") cfg.improve = true;
    if (mode === "improve") {
      cfg.warmStart = true;
      cfg.useLNS    = true;
    }
    const cb = current && current.onConfirm;
    close();
    current = null;
    if (cb) {
      try { cb(cfg); } catch (e) { console.error(e); }
    }
  }

  function suggestComplexity(school) {
    if (!school) return null;
    const lessons  = (school.lessons  && school.lessons.length)  || 0;
    const teachers = (school.teachers && school.teachers.length) || 0;
    const classes  = (school.classes  && school.classes.length)  || 0;
    if (lessons > 200 || teachers > 50 || classes > 25) return "huge";
    if (lessons > 80  || teachers > 25 || classes > 12) return "large";
    return "normal";
  }
  function applySuggestedComplexity(school) {
    if (!dialog) return;
    const suggested = suggestComplexity(school);
    if (!suggested) return;
    const radios = dialog.querySelectorAll("input[name='complexity']");
    radios.forEach(r => { r.checked = (r.value === suggested); });
    // Mirror the suggestion into the preset picker (school size picks speed).
    selectPreset(PRESET_BY_COMPLEXITY[suggested] || "balanced");
  }

  function open(opts) {
    current = opts || {};
    if (!host) build();
    setMode(current.defaultMode || "best");
    const targetSchool = current.school || (global.APP && global.APP.school) || null;
    setSummary(targetSchool);
    applySuggestedComplexity(targetSchool);
    host.classList.add("is-open");
    host.setAttribute("aria-hidden", "false");
    requestAnimationFrame(() => {
      const f = dialog.querySelector("#csu-prelaunch-start");
      if (f) f.focus();
    });
  }
  function close() {
    if (!host) return;
    host.classList.remove("is-open");
    host.setAttribute("aria-hidden", "true");
  }

  global.SolverUI = global.SolverUI || {};
  global.SolverUI.PreLaunch = { open, close };
})(typeof window !== "undefined" ? window : globalThis);
