// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "./state.js";
import "./components/landing_demo.js";
import "./entities/dialog_shell.js";
import "./wizard/create_new.js";

window.StartScreen = (function () {
  "use strict";

  const AUTO_KEY = "chronexa.autosave.v1";
  const SNAP_KEY = "chronexa.snapshots.v1";
  const SWATCHES = [
    "var(--chrx-accent)",
    "var(--chrx-green)",
    "var(--chrx-orange)",
    "var(--chrx-purple)",
  ];

  function render() {
    wireOpenCard();
    wireSampleInfo();
    renderRecent();
    mountLandingDemo();
  }

  function mountLandingDemo() {
    const mount = document.getElementById("landing-demo-mount");
    if (!mount || !window.LandingDemo || typeof window.LandingDemo.mount !== "function") return;
    // Wire the stepper BEFORE mounting: the reduced-motion path renders its
    // final frame and emits "ready" during mount(), and the stepper has to
    // hear that to press the right stage button for that frame.
    wireDemoStages(mount);
    window.LandingDemo.mount(mount);
  }

  // Stage-machine stepper (landing redesign 2026-08-02): the buttons freeze the
  // demo loop on a stage; the footer mode button resumes the auto loop.
  // They swap no panel, so the button state is aria-pressed, not aria-selected.
  function wireDemoStages(mount) {
    const panel = mount.closest(".chrx-landing-demo");
    if (!panel || panel.dataset.stagesWired === "1") return;
    panel.dataset.stagesWired = "1";

    const tabs = Array.from(panel.querySelectorAll(".chrx-appwindow__stage[data-stage]"));
    const modeBtn = panel.querySelector("[data-demo-mode]");
    const ORDER = (window.LandingDemo && window.LandingDemo.STAGES) ||
      ["lessons", "solve", "conflict", "reassign", "ready"];
    const reduced = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    if (modeBtn && reduced) modeBtn.hidden = true;

    tabs.forEach((tab) => {
      tab.addEventListener("click", () => {
        if (typeof window.LandingDemo.setStage === "function") {
          window.LandingDemo.setStage(mount, tab.dataset.stage);
        }
      });
    });

    if (modeBtn) {
      modeBtn.addEventListener("click", () => {
        if (typeof window.LandingDemo.resume === "function") window.LandingDemo.resume(mount);
      });
    }

    mount.addEventListener("landing-demo:stage", (e) => {
      const stage = e.detail && e.detail.stage;
      const idx = ORDER.indexOf(stage);
      const frozen = typeof window.LandingDemo.isFrozen === "function" && window.LandingDemo.isFrozen(mount);
      tabs.forEach((tab, i) => {
        tab.setAttribute("aria-pressed", String(i === idx));
        tab.classList.toggle("is-done", idx > 0 && i < idx);
      });
      if (modeBtn && !reduced) {
        modeBtn.setAttribute("aria-pressed", String(!frozen));
        modeBtn.textContent = frozen ? "▶ resume auto" : "auto · 12s loop";
      }
    });
  }

  function wireOpenCard() {
    const card = document.getElementById("start-open-card");
    const input = document.getElementById("xml-file");
    if (!card || !input || card.dataset.startWired === "1") return;
    card.dataset.startWired = "1";
    card.setAttribute("role", "button");
    // Name the accepted formats here too: this control is the landing page's
    // only route to a file picker that greys out .dif / .xlsx.
    card.setAttribute("aria-label", "Open timetable — " + INPUT_FORMATS);

    card.addEventListener("click", (e) => {
      if (e.target === input) return;
      e.preventDefault();
      input.click();
    });

    card.addEventListener("keydown", (e) => {
      if (e.key !== "Enter" && e.key !== " ") return;
      e.preventDefault();
      input.click();
    });
    card.addEventListener("dragover", (e) => {
      e.preventDefault();
      card.classList.add("is-dragging");
    });
    card.addEventListener("dragleave", () => card.classList.remove("is-dragging"));
    card.addEventListener("drop", (e) => {
      e.preventDefault();
      card.classList.remove("is-dragging");
      takeFiles(e.dataTransfer, input);
    });

    wireHeroDropZone(input);
  }

  // A drop is a file drag only. Dragging selected text, a link or an image
  // around the page must never arm the drop state.
  function isFileDrag(dt) {
    if (!dt) return false;
    const types = dt.types;
    if (!types) return false;
    return typeof types.includes === "function"
      ? types.includes("Files")
      : Array.prototype.indexOf.call(types, "Files") !== -1;
  }

  function takeFiles(dt, input) {
    if (!dt || !dt.files || !dt.files.length) return;
    input.files = dt.files;
    input.dispatchEvent(new Event("change", { bubbles: true }));
  }

  /* The hero is the product's own argument, so it is also the drop target: a
     visitor can drop their real timetable onto the board instead of hunting for
     the button. The frame and prompt are the only added surface; the copy
     recedes while a drag is armed so the state reads as a mode.
     Both hero and the rest of the landing swallow the drop so a misdrop below
     the fold cannot navigate the browser to the file and lose the session. */
  function wireHeroDropZone(input) {
    const hero = document.querySelector(".chrx-lattice-hero");
    const landing = document.querySelector(".chrx-landing");
    if (!hero || !landing || hero.dataset.dropWired === "1") return;
    hero.dataset.dropWired = "1";

    // dragenter/dragleave fire for every descendant, so depth is counted rather
    // than toggled — otherwise moving across one tile drops the armed state.
    let depth = 0;
    const clear = () => { depth = 0; hero.classList.remove("is-file-over"); };

    hero.addEventListener("dragenter", (e) => {
      if (!isFileDrag(e.dataTransfer)) return;
      depth += 1;
      hero.classList.add("is-file-over");
    });
    hero.addEventListener("dragover", (e) => {
      if (!isFileDrag(e.dataTransfer)) return;
      e.preventDefault();
      e.dataTransfer.dropEffect = "copy";
    });
    hero.addEventListener("dragleave", (e) => {
      if (!isFileDrag(e.dataTransfer)) return;
      depth -= 1;
      // relatedTarget === null means the pointer left the window entirely.
      if (depth <= 0 || e.relatedTarget === null) clear();
    });
    hero.addEventListener("drop", (e) => {
      e.preventDefault();
      clear();
      takeFiles(e.dataTransfer, input);
    });

    landing.addEventListener("dragover", (e) => {
      if (isFileDrag(e.dataTransfer)) e.preventDefault();
    });
    landing.addEventListener("drop", (e) => {
      if (!isFileDrag(e.dataTransfer)) return;
      e.preventDefault();
      clear();
      takeFiles(e.dataTransfer, input);
    });
    // Dragging out of the window, or releasing outside any handler, must not
    // leave the hero stuck in its armed state.
    window.addEventListener("dragend", clear);
    window.addEventListener("blur", clear);
  }

  // The accepted input formats, stated in exactly one place. main.js reuses
  // this string for the #xml-status rejection message (start_screen.js is
  // imported by main.js before boot(), so window.StartScreen is always set).
  const INPUT_FORMATS = "Opens .xml (Classic/ASC, GP-Untis) and .har files.";
  const EXPORT_FORMATS = "GP-Untis DIF, Excel, HTML, ICS, PowerSchool, and Atlantis ROZ are export formats.";

  let sampleInfoDialog = null;
  let pickerDialog = null;

  // ── Dialog focus contract ────────────────────────────────────────────────
  // EntityDialog.openSheet() (js/ui/entities/dialog_shell.js) mounts a modal
  // scrim but registers its Escape handler only while a full EntityDialog is
  // open, and it never moves focus or contains Tab. Both landing dialogs
  // therefore hung: focus stayed on the trigger, Escape did nothing, and Tab
  // walked the page behind the scrim. This gives them the aria-modal
  // contract they already claim: focus enters, Tab is trapped, Escape closes
  // through one shared close path, focus returns to the trigger.
  function dialogFocusables(root) {
    return Array.from(root.querySelectorAll(
      'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
    )).filter((el) => el.getClientRects().length > 0);
  }

  function bindDialogFocus(root, opts) {
    opts = opts || {};
    let closed = false;

    function finish() {
      if (closed) return;
      closed = true;
      document.removeEventListener("keydown", onKey, true);
      if (typeof opts.onClose === "function") opts.onClose();
      const back = opts.restoreTo;
      // Only refocus something still on screen: picking a template navigates
      // away from the landing, and focus must not be dragged backwards.
      if (back && back.isConnected && back.getClientRects().length && typeof back.focus === "function") {
        try { back.focus(); } catch (e) { /* non-fatal */ }
      }
    }

    function onKey(e) {
      // Closed by another route (e.g. a template was chosen) — just settle.
      if (!root.isConnected) { finish(); return; }
      if (e.key === "Tab") {
        const items = dialogFocusables(root);
        if (!items.length) { e.preventDefault(); return; }
        const idx = items.indexOf(document.activeElement);
        if (idx === -1) { e.preventDefault(); (e.shiftKey ? items[items.length - 1] : items[0]).focus(); return; }
        if (e.shiftKey && idx === 0) { e.preventDefault(); items[items.length - 1].focus(); }
        else if (!e.shiftKey && idx === items.length - 1) { e.preventDefault(); items[0].focus(); }
        return;
      }
      if (e.key !== "Escape") return;
      e.preventDefault();
      // Own Escape while this dialog is the topmost surface, so the
      // EntityDialog handler in dialog_shell.js cannot race this close.
      e.stopPropagation();
      if (typeof opts.onEscape === "function") opts.onEscape();
      else finish();
    }

    document.addEventListener("keydown", onKey, true);
    const initial = opts.initial || dialogFocusables(root)[0] || root;
    try { initial.focus(); } catch (e) { /* non-fatal */ }
    return { finish, isClosed: () => closed };
  }

  function wireSampleInfo() {
    const btn = document.getElementById("start-sample-info");
    if (!btn || btn.dataset.startWired === "1") return;
    btn.dataset.startWired = "1";
    btn.addEventListener("click", openSampleInfo);
  }

  function renderRecent() {
    const section = document.getElementById("start-recent-section");
    const listEl = document.getElementById("start-recent-list");
    if (!section || !listEl) return;

    const filterEl = document.getElementById("start-recent-filter");
    const entries = collectRecent().slice(0, 4);
    if (!entries.length) {
      section.classList.add("hidden");
      listEl.innerHTML = "";
      if (filterEl) filterEl.hidden = true;
      return;
    }

    section.classList.remove("hidden");

    // §3.5: filter input appears once the list is long enough to need one.
    if (filterEl) {
      filterEl.hidden = entries.length <= 3;
      if (filterEl.dataset.wired !== "1") {
        filterEl.dataset.wired = "1";
        filterEl.addEventListener("input", renderRecent);
      }
    }
    const query = filterEl && !filterEl.hidden ? filterEl.value.trim().toLowerCase() : "";
    const visible = query
      ? entries.filter((entry) => entry.schoolName.toLowerCase().includes(query))
      : entries;

    listEl.innerHTML = "";
    visible.forEach((entry, idx) => {
      const row = document.createElement("button");
      row.type = "button";
      row.className = "chrx-start-recent__row";
      const classCount = Array.isArray(entry.payload && entry.payload.classes)
        ? entry.payload.classes.length
        : null;
      row.innerHTML = `
        <span class="chrx-start-recent__swatch" aria-hidden="true"></span>
        <span class="chrx-start-recent__name"></span>
        <span class="chrx-start-recent__pill">${entry.source === "autosave" ? "auto" : "snap"}</span>
        ${classCount != null ? `<span class="chrx-start-recent__pill chrx-start-recent__pill--count">${classCount} classes</span>` : ""}
        <span class="chrx-start-recent__time"></span>
      `;
      row.querySelector(".chrx-start-recent__swatch").style.setProperty("--start-swatch", SWATCHES[idx % SWATCHES.length]);
      row.querySelector(".chrx-start-recent__name").textContent = entry.schoolName;
      row.querySelector(".chrx-start-recent__time").textContent = relativeTime(entry.timeMs);
      row.addEventListener("click", () => restoreRecent(entry));
      listEl.appendChild(row);
    });
  }

  function collectRecent() {
    const entries = [];
    const auto = readJSON(AUTO_KEY);
    if (auto && auto.payload) {
      entries.push(normalizeEntry({
        id: "autosave",
        source: "autosave",
        ts: auto.ts,
        schoolName: auto.schoolName,
        payload: auto.payload,
      }));
    }

    const snaps = readJSON(SNAP_KEY);
    if (Array.isArray(snaps)) {
      snaps.forEach((snap) => {
        if (!snap || !snap.payload) return;
        entries.push(normalizeEntry({
          id: snap.id || "snapshot-" + snap.ts,
          source: "snapshot",
          ts: snap.ts,
          schoolName: snap.school || snap.schoolName,
          payload: snap.payload,
        }));
      });
    }

    return entries
      .filter((entry) => entry && entry.payload && entry.timeMs)
      .sort((a, b) => b.timeMs - a.timeMs);
  }

  function normalizeEntry(entry) {
    const payload = entry.payload || {};
    return {
      id: entry.id,
      source: entry.source,
      timeMs: toMillis(entry.ts),
      schoolName: entry.schoolName || payload.schoolName || "(untitled)",
      payload,
    };
  }

  function restoreRecent(entry) {
    const restored = entry.source === "autosave" && window.AutoSave && window.AutoSave.restore
      ? (window.AutoSave.restore() || entry)
      : entry;
    if (!restored || !restored.payload) {
      setStatus("Could not restore that timetable.", "error");
      return;
    }

    const APP = window.APP || (window.APP = {});
    APP.school = clone(restored.payload);
    if (window.CreateNew && window.CreateNew.refreshIndex) window.CreateNew.refreshIndex();
    if (window.CreateNew && window.CreateNew.ensureColors) window.CreateNew.ensureColors();
    document.querySelectorAll(".needs-school").forEach((btn) => { btn.disabled = false; });

    const detail = { source: "start-recent" };
    window.dispatchEvent(new CustomEvent("app:school-loaded", { detail }));
    document.dispatchEvent(new CustomEvent("app:school-loaded", { detail }));
    setStatus(`Restored ${APP.school.schoolName || "timetable"}.`, "ok");
    renderRecent();
  }

  function openSampleInfo() {
    if (sampleInfoDialog) return;
    const title = "Sample school";
    const paragraphs = [
      "The bundled demo contains a realistic school setup with teachers, classes, rooms, subjects, lessons, bell periods, and placed timetable cards.",
      "It loads locally from this app, can be edited like any timetable, and is useful for trying the editor before opening your own file.",
      INPUT_FORMATS + " " + EXPORT_FORMATS,
    ];

    const D = window.EntityDialog;
    if (D && D.openSheet && D.el) {
      try {
        const before = new Set(document.querySelectorAll(".chrx-ent-sheet-scrim"));
        D.openSheet(D.el("div", { class: "chrx-start-info" },
          ...paragraphs.map((text) => D.el("p", null, text))
        ), { title });
        const scrim = Array.from(document.querySelectorAll(".chrx-ent-sheet-scrim"))
          .find((node) => !before.has(node));
        const sheet = scrim && scrim.querySelector(".chrx-ent-sheet");
        if (sheet) {
          adoptSampleInfoSheet(D, scrim, sheet);
          return;
        }
      } catch (e) {
        // Fall through to the standalone modal.
      }
    }

    const modal = document.createElement("div");
    modal.className = "chrx-start-modal";
    modal.innerHTML = `
      <div class="chrx-start-modal__panel" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}">
        <h3>${escapeHtml(title)}</h3>
        ${paragraphs.map((text) => `<p>${escapeHtml(text)}</p>`).join("")}
        <button type="button" class="chrx-btn chrx-btn--primary">Done</button>
      </div>
    `;
    document.body.appendChild(modal);

    const panel = modal.querySelector(".chrx-start-modal__panel");
    const close = () => {
      if (modal.isConnected) modal.remove();
      if (sampleInfoDialog) sampleInfoDialog.finish();
    };
    modal.addEventListener("click", (e) => { if (e.target === modal) close(); });
    panel.querySelector("button").addEventListener("click", close);
    sampleInfoDialog = bindDialogFocus(panel, {
      restoreTo: document.getElementById("start-sample-info"),
      onEscape: close,
      onClose: () => { sampleInfoDialog = null; },
    });
  }

  // Take over the EntityDialog sheet so × , scrim click and Escape all run one
  // close path, and focus enters/returns the way aria-modal="true" promises.
  function adoptSampleInfoSheet(D, scrim, sheet) {
    const heading = sheet.querySelector("h3");
    if (heading) {
      if (!heading.id) heading.id = "start-sample-info-title";
      sheet.setAttribute("aria-labelledby", heading.id);
    }

    function closeInfo() {
      if (scrim.isConnected) {
        if (typeof D.closeSheet === "function") D.closeSheet();
        else scrim.remove();
      }
      if (sampleInfoDialog) sampleInfoDialog.finish();
    }

    const x = sheet.querySelector(".chrx-ent-sheet__x");
    if (x) x.onclick = (e) => { e.preventDefault(); closeInfo(); };
    scrim.onclick = (e) => { if (e.target === scrim) closeInfo(); };

    sampleInfoDialog = bindDialogFocus(sheet, {
      restoreTo: document.getElementById("start-sample-info"),
      initial: x,
      onEscape: closeInfo,
      onClose: () => { sampleInfoDialog = null; },
    });
  }

  // The school-template picker (js/ui/onboarding/school_templates.js) is built
  // from bare divs — no dialog role, no close control, and Escape did nothing.
  // Its trigger lives in wiring.js, so the panel is upgraded here, from JS.
  function upgradeTemplatePicker(root) {
    if (!root || root.dataset.chrxPickerReady === "1") return;
    const panel = root.querySelector(".chrx-tpl-modal__panel");
    if (!panel) return;
    root.dataset.chrxPickerReady = "1";

    const heading = panel.querySelector("h3");
    if (heading) {
      if (!heading.id) heading.id = "chrx-tpl-picker-title";
      panel.setAttribute("aria-labelledby", heading.id);
    }
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-modal", "true");
    // Focus the container, not the first tile: this dialog is usually opened
    // with Enter/Space, and auto-focusing an option would make that keystroke
    // select a school type by accident.
    panel.tabIndex = -1;

    function closePicker() {
      if (root.isConnected) root.remove();
      if (pickerDialog) pickerDialog.finish();
    }

    // Visible dismiss. Reuses the picker's own card class (no new CSS) and
    // names the consequence, so "cancel" is never a mystery.
    const dismiss = document.createElement("button");
    dismiss.type = "button";
    dismiss.className = "chrx-tpl-card";
    dismiss.textContent = "✕ Cancel — keep my current school";
    dismiss.addEventListener("click", closePicker);
    panel.appendChild(dismiss);

    root.onclick = (e) => { if (e.target === root) closePicker(); };

    pickerDialog = bindDialogFocus(panel, {
      restoreTo: document.getElementById("cta-build-new") || document.activeElement,
      initial: panel,
      onEscape: closePicker,
      onClose: () => { pickerDialog = null; },
    });
  }

  function setStatus(message, tone) {
    const status = document.getElementById("xml-status");
    if (!status) return;
    const cls = tone === "error" ? "text-rose-700" : "text-emerald-700";
    status.innerHTML = `<span class="${cls} font-semibold">${escapeHtml(message)}</span>`;
  }

  function readJSON(key) {
    try {
      const raw = localStorage.getItem(key);
      return raw ? JSON.parse(raw) : null;
    } catch (e) {
      return null;
    }
  }

  function toMillis(value) {
    if (typeof value === "number" && isFinite(value)) return value;
    const parsed = Date.parse(value || "");
    return isFinite(parsed) ? parsed : 0;
  }

  function relativeTime(timeMs) {
    const diff = Math.max(0, Date.now() - timeMs);
    const minute = 60 * 1000;
    const hour = 60 * minute;
    const day = 24 * hour;
    if (diff < minute) return "just now";
    if (diff < hour) return Math.max(1, Math.round(diff / minute)) + " min ago";
    if (diff < day) return Math.max(1, Math.round(diff / hour)) + " hr ago";
    if (diff < 2 * day) return "yesterday";
    return Math.round(diff / day) + " days ago";
  }

  function clone(value) {
    if (typeof structuredClone === "function") return structuredClone(value);
    return JSON.parse(JSON.stringify(value));
  }

  function escapeHtml(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, (c) =>
      ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  }

  return {
    render,
    collectRecent,
    openSampleInfo,
    upgradeTemplatePicker,
    INPUT_FORMATS,
  };
})();

// [vite-esm] exports auto-generated by the 2026-07 Vite migration.
export const StartScreen = window.StartScreen;
