// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "../state.js";

/* Entity field gaps from the W15 live Classic walk.
 *
 * The live walk discovered concrete fields the offline docs missed.
 * Rather than reopening every frozen entity dialog file, this module
 * decorates them from outside via MutationObserver — same pattern as
 * smart_defaults.js — and slots the missing inputs into the edit sheet.
 *
 * Gap matrix shipped here:
 *   Classroom: `bells` (FK to bells), `nearbyClassroomIds` (multi-select)
 *   Teacher:   `title` (free text, e.g. "Mr."/"Dr."), `nameSuffix`,
 *              `gender` (enum), `fontColorsScreen / fontColorPrint / fontColorPrint2`
 *   Class:     `grade` (FK to grades entity), `printSubjectPictures` (bool)
 *
 * Each field stays in a local draft while the sheet is open.  The existing
 * Save submit is decorated so all gap fields are applied together in one
 * APP.mutate transaction; cancelling a sheet therefore cannot leak edits.
 */
(function (global) {
  "use strict";

  function el(tag, attrs, ...kids) {
    const n = document.createElement(tag);
    if (attrs) for (const k in attrs) {
      const v = attrs[k]; if (v == null) continue;
      if (k === "class") n.className = v;
      else if (k.startsWith("on") && typeof v === "function") n.addEventListener(k.slice(2), v);
      else n.setAttribute(k, v);
    }
    for (const c of kids) if (c != null && c !== false)
      n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    return n;
  }

  function findSheet() {
    return document.querySelector(".chrx-ent-sheet, .chrx-edit-sheet");
  }

  /* Inserts a [label] [control] row before the [Cancel | Save] buttons */
  function addFieldRow(sheet, label, control) {
    if (!sheet) return;
    const row = el("div", { class: "chrx-fieldgap-row",
      style: "display:flex;gap:10px;align-items:center;margin:6px 0;padding:4px 12px" },
      el("label", { style: "min-width:140px;font-size:13px;color:#475569;font-weight:500" }, label),
      control);
    // Append into the sheet body (before footer if there is one)
    const footer = sheet.querySelector("footer, .chrx-ent-sheet__foot, .chrx-ent-form__foot");
    if (footer) footer.parentNode.insertBefore(row, footer);
    else sheet.appendChild(row);
  }

  function inferEntity(dlg) {
    const h = dlg.querySelector("h2, h3, header h2, header h3, .chrx-ent-head h2");
    if (!h) return null;
    const t = (h.textContent || "").toLowerCase();
    if (t.includes("teacher")) return "teacher";
    if (t.includes("classroom") || t.includes("room")) return "classroom";
    if (t.includes("class")) return "class";
    return null;
  }

  function findCurrentRow(kind, sheetEl) {
    const APP = global.APP;
    if (!APP?.school) return null;
    const pool = APP.school[kind + "s"] || APP.school[kind + "rooms"];
    if (!pool) return null;
    // A new sheet can be opened while another collection row remains selected.
    // Resolve the sheet kind/title before consulting that selection so a new
    // save never decorates the previously selected entity.
    const titleText = (sheetEl?.querySelector(".chrx-ent-sheet__head h3, header h2, header h3")?.textContent || "").trim().toLowerCase();
    if (titleText.startsWith("new ")) return null;
    // The collection dialog keeps the edited row selected. Prefer that stable
    // id; matching the collection title ("Teachers") would otherwise fall
    // through to an unrelated last row.
    const dlg = document.querySelector(".chrx-ent-dialog");
    const selectedId = dlg?.querySelector(".chrx-ent-tr.is-selected")?.dataset.id;
    if (selectedId) {
      const selected = pool.find(r => String(r.id) === String(selectedId));
      if (selected) return selected;
    }
    // For standalone/new sheets there may be no selected table row. Match the
    // actual sheet title (for example, "Edit teacher — Ms. Rao").
    for (const r of pool) {
      const nm = (r.name || "").toLowerCase();
      if (nm && titleText.includes(nm)) return r;
    }
    return null;
  }

  function decorate(sheetEl) {
    if (!sheetEl || sheetEl.dataset.chrxFieldGapsDone) return;
    
    const sheetTitle = (sheetEl.querySelector(".chrx-ent-sheet__head h3, header h2, header h3")?.textContent || "").toLowerCase();
    if (!sheetTitle.startsWith("new ") && !sheetTitle.startsWith("edit ")) return;

    const dlg = sheetEl.closest(".chrx-ent-dialog");
    if (!dlg) return;
    const kind = inferEntity(dlg);
    if (!kind) return;
    sheetEl.dataset.chrxFieldGapsDone = "1";

    // New-row sheets do not have a backing entity until the host dialog's
    // Save handler runs.  Keep the draft independent of that row and resolve
    // the newly-created entity from its collection at submit time.
    const row = findCurrentRow(kind, sheetEl) || {};
    const APP = global.APP;
    const school = APP.school;
    const draft = {
      title: row.title || row.nameprefix || "",
      nameSuffix: row.nameSuffix || row.namesuffix || "",
      gender: row.gender || "",
      fontColorScreen: row.fontColorScreen || "#000000",
      fontColorPrint: row.fontColorPrint || "#000000",
      fontColorPrint2: row.fontColorPrint2 || "#000000",
      bellId: row.bellId || "",
      nearbyClassroomIds: Array.isArray(row.nearbyClassroomIds) ? row.nearbyClassroomIds.slice() : [],
      gradeId: row.gradeId || "",
      printSubjectPictures: !!row.printSubjectPictures,
    };

    if (kind === "teacher") {
      // Title (nameprefix)
      const fTitle = el("input", { type: "text", maxlength: "12",
        value: draft.title,
        placeholder: "Mr. / Mrs. / Dr.",
        oninput: e => draft.title = e.target.value.trim(),
        style: "padding:5px 8px;border:1px solid #cbd5e1;border-radius:5px;font-size:13px;flex:1" });
      addFieldRow(sheetEl, "Title", fTitle);

      // Name suffix
      const fSuf = el("input", { type: "text", maxlength: "12",
        value: draft.nameSuffix,
        placeholder: "Jr. / Sr.",
        oninput: e => draft.nameSuffix = e.target.value.trim(),
        style: "padding:5px 8px;border:1px solid #cbd5e1;border-radius:5px;font-size:13px;flex:1" });
      addFieldRow(sheetEl, "Name suffix", fSuf);

      // Gender
      const fGender = el("select", {
        onchange: e => draft.gender = e.target.value,
        style: "padding:5px 8px;border:1px solid #cbd5e1;border-radius:5px;font-size:13px;flex:1" });
      ["", "m", "f", "x"].forEach(v => {
        const o = el("option", { value: v }, v === "" ? "—" : v === "m" ? "Male" : v === "f" ? "Female" : "Other");
        if (draft.gender === v) o.setAttribute("selected", "selected");
        fGender.appendChild(o);
      });
      addFieldRow(sheetEl, "Gender", fGender);

      // 3 print colors (Specify font colors)
      ["fontColorScreen", "fontColorPrint", "fontColorPrint2"].forEach((key, i) => {
        const fc = el("input", { type: "color",
          value: draft[key],
          oninput: e => draft[key] = e.target.value,
          style: "width:60px;height:24px;border:1px solid #cbd5e1;border-radius:5px" });
        addFieldRow(sheetEl, ["Screen color", "Print color 1", "Print color 2"][i], fc);
      });
    }
    else if (kind === "classroom") {
      // Bells (FK to bells)
      const fBell = el("select", {
        onchange: e => draft.bellId = e.target.value,
        style: "padding:5px 8px;border:1px solid #cbd5e1;border-radius:5px;font-size:13px;flex:1" });
      fBell.appendChild(el("option", { value: "" }, "Use school default"));
      (school.bells || []).forEach(b => {
        const o = el("option", { value: b.id }, b.name || b.id);
        if (draft.bellId === b.id) o.setAttribute("selected", "selected");
        fBell.appendChild(o);
      });
      addFieldRow(sheetEl, "Bell schedule", fBell);

      // Nearby classrooms (multi-select via checkbox list)
      const nearby = new Set(draft.nearbyClassroomIds);
      const fNearbyWrap = el("div", { style: "flex:1;max-height:120px;overflow-y:auto;border:1px solid #cbd5e1;border-radius:5px;padding:4px 8px;font-size:12px" });
      (school.classrooms || []).forEach(c => {
        if (c.id === row.id) return; // skip self
        const cb = el("input", { type: "checkbox",
          checked: nearby.has(c.id) ? "checked" : null,
          onchange: e => {
            if (e.target.checked) nearby.add(c.id); else nearby.delete(c.id);
            draft.nearbyClassroomIds = Array.from(nearby);
          } });
        const label = el("label", { style: "display:flex;align-items:center;gap:6px;padding:2px 0;cursor:pointer" }, cb, c.name);
        fNearbyWrap.appendChild(label);
      });
      addFieldRow(sheetEl, "Nearby classrooms", fNearbyWrap);
    }
    else if (kind === "class") {
      // Grade dropdown
      const fGrade = el("select", {
        onchange: e => draft.gradeId = e.target.value,
        style: "padding:5px 8px;border:1px solid #cbd5e1;border-radius:5px;font-size:13px;flex:1" });
      fGrade.appendChild(el("option", { value: "" }, "—"));
      (school.grades || []).forEach(g => {
        const o = el("option", { value: g.id }, g.name || g.id);
        if (draft.gradeId === g.id) o.setAttribute("selected", "selected");
        fGrade.appendChild(o);
      });
      addFieldRow(sheetEl, "Grade", fGrade);

      // Print subject pictures toggle
      const fPSP = el("input", { type: "checkbox",
        checked: draft.printSubjectPictures ? "checked" : null,
        onchange: e => draft.printSubjectPictures = e.target.checked });
      addFieldRow(sheetEl, "Print subject pictures", fPSP);
    }

    // Ask the dialog shell to wrap the host save and this post-save application
    // in one transaction. The host save runs first so a new row exists before
    // we resolve it; nested APP.mutate calls fold into the outer step.
    const form = sheetEl.querySelector("form");
    if (form && !form.dataset.chrxFieldgapHooked) {
      form.dataset.chrxFieldgapHooked = "1";
      form.__chrxSaveTransaction = "Save entity fields";
      form.__chrxAfterSave = () => {
        const currentSchool = APP.school;
        const pool = currentSchool?.[kind + "s"] || currentSchool?.[kind + "rooms"] || [];
        const current = row.id
          ? (pool.find(item => item.id === row.id) || null)
          : pool[pool.length - 1];
        if (!current) return;
        const empty = (value) => value ? value : undefined;
        if (kind === "teacher") {
          current.title = empty(draft.title);
          current.nameSuffix = empty(draft.nameSuffix);
          current.gender = empty(draft.gender);
          current.fontColorScreen = empty(draft.fontColorScreen);
          current.fontColorPrint = empty(draft.fontColorPrint);
          current.fontColorPrint2 = empty(draft.fontColorPrint2);
        } else if (kind === "classroom") {
          current.bellId = empty(draft.bellId);
          current.nearbyClassroomIds = draft.nearbyClassroomIds.length ? draft.nearbyClassroomIds.slice() : undefined;
        } else if (kind === "class") {
          current.gradeId = empty(draft.gradeId);
          current.printSubjectPictures = !!draft.printSubjectPictures;
        }
        APP.audit?.append?.({
          entity: kind + "s", op: "field-gap-save", id: current.id,
          fields: Object.keys(draft),
        });
      };
    }
  }

  function startObserver() {
    if (global.__chrxFieldGapsObserver) return;
    const obs = new MutationObserver(muts => {
      for (const m of muts) {
        for (const n of m.addedNodes) {
          if (n.nodeType !== 1) continue;
          if (n.classList?.contains("chrx-ent-sheet")) decorate(n);
          else if (n.querySelector) {
            const s = n.querySelector(".chrx-ent-sheet, .chrx-edit-sheet");
            if (s) decorate(s);
          }
        }
      }
    });
    obs.observe(document.body, { childList: true, subtree: true });
    global.__chrxFieldGapsObserver = obs;
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", startObserver);
  } else { startObserver(); }

  global.EntityFieldGaps = { decorate };
})(window);

// Chronexa Web

// [vite-esm] exports auto-generated by the 2026-07 Vite migration.
export const EntityFieldGaps = window.EntityFieldGaps;
export const __chrxFieldGapsObserver = window.__chrxFieldGapsObserver;
