// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "../state.js";

/* Standalone HTML exporter — generates a self-contained HTML file with the
 * full timetable embedded (no external deps, no JS, just print-friendly HTML
 * + CSS). Schools email this to teachers / parents / website.
 *
 * Ports Swift's ClassicHTMLExporter.swift. Triggered via `app:export-html` event.
 * Output filename derives from school.schoolName.
 */
const APP = (typeof window !== "undefined" ? window.APP : null) || {};
const notify = (typeof window !== "undefined" && window._chrxNotify) || console.log;
const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, c =>
      ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
  }

  function buildClassGrid(school, classRow) {
    const periods = (school.bell && school.bell.periods) || [];
    const cards = school.cards || [];
    const lessonById = (school._idx && school._idx.lessonById) ||
      Object.fromEntries((school.lessons || []).map(l => [l.id, l]));
    const subjectById = (school._idx && school._idx.subjectById) ||
      Object.fromEntries((school.subjects || []).map(s => [s.id, s]));
    const teacherById = (school._idx && school._idx.teacherById) ||
      Object.fromEntries((school.teachers || []).map(t => [t.id, t]));
    const roomById = (school._idx && school._idx.classroomById) ||
      Object.fromEntries((school.classrooms || []).map(r => [r.id, r]));

    const grid = Array.from({ length: 6 }, () => Array(periods.length).fill(null));
    for (const c of cards) {
      const lesson = lessonById[c.lessonId];
      if (!lesson) continue;
      if (!(lesson.classIds || []).includes(classRow.id)) continue;
      // card.period is 1-based (per DATA_SHAPES + parse_timetable_xml.js);
      // grid columns are 0-based. Without this -1 the first period rendered
      // as the second column and the last period was silently dropped.
      const pIdx = (c.period | 0) - 1;
      if (c.day >= 6 || pIdx < 0 || pIdx >= periods.length) continue;
      const subj = subjectById[lesson.subjectId] || {};
      const teachers = (lesson.teacherIds || []).map(t => teacherById[t]?.short || teacherById[t]?.name || "—").join(", ");
      const room = c.classroomId ? (roomById[c.classroomId]?.short || roomById[c.classroomId]?.name || "") : "";
      grid[c.day][pIdx] = { subject: subj.short || subj.name || "?", color: subj.color || "#94a3b8", teachers, room };
    }

    let html = `<h2>${esc(classRow.name || classRow.short)}</h2><table class="tt">`;
    html += `<thead><tr><th>Day</th>${periods.map((p, i) => `<th>P${i + 1}</th>`).join("")}</tr></thead><tbody>`;
    for (let d = 0; d < 6; d++) {
      html += `<tr><th class="day">${DAYS[d]}</th>`;
      for (let p = 0; p < periods.length; p++) {
        const c = grid[d][p];
        if (c) {
          html += `<td class="cell" style="background:${esc(c.color)}22;border-left:4px solid ${esc(c.color)}"><div class="subj">${esc(c.subject)}</div><div class="meta">${esc(c.teachers)}</div>${c.room ? `<div class="room">${esc(c.room)}</div>` : ""}</td>`;
        } else {
          html += `<td class="cell empty"></td>`;
        }
      }
      html += "</tr>";
    }
    html += "</tbody></table>";
    return html;
  }

  function buildTeacherGrid(school, teacherRow) {
    const periods = (school.bell && school.bell.periods) || [];
    const cards = school.cards || [];
    const lessonById = (school._idx && school._idx.lessonById) ||
      Object.fromEntries((school.lessons || []).map(l => [l.id, l]));
    const subjectById = (school._idx && school._idx.subjectById) ||
      Object.fromEntries((school.subjects || []).map(s => [s.id, s]));
    const classById = (school._idx && school._idx.classById) ||
      Object.fromEntries((school.classes || []).map(c => [c.id, c]));
    const roomById = (school._idx && school._idx.classroomById) ||
      Object.fromEntries((school.classrooms || []).map(r => [r.id, r]));

    const grid = Array.from({ length: 6 }, () => Array(periods.length).fill(null));
    for (const c of cards) {
      const lesson = lessonById[c.lessonId];
      if (!lesson) continue;
      if (!(lesson.teacherIds || []).includes(teacherRow.id)) continue;
      const pIdx = (c.period | 0) - 1;
      if (c.day >= 6 || pIdx < 0 || pIdx >= periods.length) continue;
      const subj = subjectById[lesson.subjectId] || {};
      const classes = (lesson.classIds || []).map(cid => classById[cid]?.short || classById[cid]?.name || "—").join(", ");
      const room = c.classroomId ? (roomById[c.classroomId]?.short || roomById[c.classroomId]?.name || "") : "";
      grid[c.day][pIdx] = { subject: subj.short || subj.name || "?", color: subj.color || "#94a3b8", classes, room };
    }

    let html = `<h2>${esc(teacherRow.name || teacherRow.short)}</h2><table class="tt">`;
    html += `<thead><tr><th>Day</th>${periods.map((p, i) => `<th>P${i + 1}</th>`).join("")}</tr></thead><tbody>`;
    for (let d = 0; d < 6; d++) {
      html += `<tr><th class="day">${DAYS[d]}</th>`;
      for (let p = 0; p < periods.length; p++) {
        const c = grid[d][p];
        if (c) {
          html += `<td class="cell" style="background:${esc(c.color)}22;border-left:4px solid ${esc(c.color)}"><div class="subj">${esc(c.subject)}</div><div class="meta">${esc(c.classes)}</div>${c.room ? `<div class="room">${esc(c.room)}</div>` : ""}</td>`;
        } else {
          html += `<td class="cell empty"></td>`;
        }
      }
      html += "</tr>";
    }
    html += "</tbody></table>";
    return html;
  }

  export function buildHtmlExport(school, scope = { type: "all" }) {
    const scopeType = typeof scope === "string" ? scope : (scope && scope.type) || "all";
    const scopeId = typeof scope === "object" ? scope.id : null;

    let body = "";
    if (scopeType === "teacher") {
      const teachers = (school.teachers || []).filter(t => !scopeId || t.id === scopeId);
      body = teachers.map(t => buildTeacherGrid(school, t)).join("\n");
    } else {
      let classes = school.classes || [];
      if (scopeType === "class" && scopeId) {
        classes = classes.filter(c => c.id === scopeId);
      }
      body = classes.map(c => buildClassGrid(school, c)).join("\n");
    }
    const title = `${school.schoolName || "Timetable"} — ${new Date().toLocaleDateString()}`;

    return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1e293b; margin: 24px; }
  h1 { color: #1e3a8a; margin-bottom: 8px; }
  h2 { color: #1e3a8a; margin-top: 28px; border-bottom: 2px solid #cbd5e1; padding-bottom: 4px; }
  table.tt { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; page-break-inside: avoid; }
  table.tt th, table.tt td { border: 1px solid #cbd5e1; padding: 6px; text-align: left; vertical-align: top; }
  table.tt thead th { background: #f1f5f9; color: #475569; font-size: 11px; text-transform: uppercase; }
  table.tt th.day { background: #f8fafc; font-weight: 600; width: 8%; }
  table.tt td.cell { min-height: 36px; }
  table.tt td.empty { background: repeating-linear-gradient(45deg, #fafafa, #fafafa 4px, #f1f5f9 4px, #f1f5f9 8px); }
  .subj { font-weight: 700; color: #0f172a; }
  .meta { color: #475569; font-size: 11px; margin-top: 2px; }
  .room { color: #94a3b8; font-size: 10px; font-style: italic; }
  @media print {
    body { margin: 12mm; }
    h1 { font-size: 18pt; }
    h2 { font-size: 14pt; page-break-before: auto; }
    table.tt { font-size: 9pt; }
  }
  .footer { text-align: center; color: #94a3b8; margin-top: 40px; font-size: 11px; }
</style>
</head><body>
<h1>${esc(school.schoolName || "Timetable")}</h1>
<p style="color:#64748b">Exported ${esc(new Date().toLocaleString())} · Chronexa Web</p>
${body}
<div class="footer">Generated by Chronexa Web — open browser timetable. https://abhishekchhetri020.github.io/chronexa-web/</div>
</body></html>`;
  }

  function buildHTML(school, scope) {
    return buildHtmlExport(school, scope);
  }

  export function exportHTML(scope = { type: "all" }) {
    const school = APP.school;
    if (!school) { notify("Open a timetable first.", "error"); return; }
    const html = buildHtmlExport(school, scope);
    const base = (school._meta?.sourceFilename || school.schoolName || "chronexa").replace(/\.xml$/i, "");
    const scopeType = typeof scope === "string" ? scope : (scope && scope.type) || "all";
    const scopeId = typeof scope === "object" ? scope.id : null;
    let suffix = "";
    if (scopeType === "class" && scopeId) {
      const c = (school.classes || []).find(x => x.id === scopeId);
      suffix = "-" + (c?.short || c?.name || scopeId).replace(/[^\w.-]+/g, "-");
    } else if (scopeType === "teacher" && scopeId) {
      const t = (school.teachers || []).find(x => x.id === scopeId);
      suffix = "-" + (t?.short || t?.name || scopeId).replace(/[^\w.-]+/g, "-");
    }
    const fname = base + suffix + ".html";
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = fname;
    document.body.appendChild(a); a.click();
    setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000);
    notify("Exported " + fname);
    return fname;
  }

  window.addEventListener("app:export-html", (e) => exportHTML(e.detail?.scope || e.detail));
  if (typeof window !== "undefined") {
    window.APP = window.APP || {};
    window.APP.io = window.APP.io || {};
    window.APP.io.exportHTML = exportHTML;
    window.APP.io.buildHtmlExport = buildHtmlExport;
  }
