// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "../state.js";
import "./grid_canvas.js";

/** PendingStrip.render(rootEl) — sticky bottom strip of un-placed cards. */
window.PendingStrip = (function () {
  "use strict";

  const GROUPS = {
    all:       { label: "All",       keyFn: () => "all" },
    subject:   { label: "Subject",   keyFn: (S,L)=>keyOf(S._idx.subjectById[L.subjectId]) },
    class:     { label: "Class",     keyFn: (S,L)=>keyOf(S._idx.classById[L.classIds[0]]) },
    teacher:   { label: "Teacher",   keyFn: (S,L)=>keyOf(S._idx.teacherById[L.teacherIds[0]]) },
    classroom: { label: "Classroom", keyFn: (S,L)=>keyOf(S._idx.classroomById[L.preferredRoomId]) },
  };

  let _state = { groupBy: "subject", filter: "" };

  function render(rootEl) {
    if (!rootEl) return;
    const S = window.APP.school;
    rootEl.classList.add("chrx-pending-strip");
    applyTrayHeight(rootEl);
    if (!S) {
      rootEl.innerHTML = `<div class="chrx-pending-empty">No timetable loaded.</div>`;
      return;
    }
    const placedCounts = countPlaced(S);
    const groups = buildGroups(S, placedCounts);

    rootEl.innerHTML = `
      <div class="chrx-pending-resize" title="Drag to resize pending cards"></div>
      ${toolbarHtml()}
      <div class="chrx-pending-scroll">
        ${groups.map(groupHtml).join("") || `<div class="chrx-pending-empty">${window.ChrxIcons ? window.ChrxIcons.svg("check", 15) : ""}Every lesson is on the timetable.</div>`}
      </div>
    `;
    wire(rootEl);
  }

  function toolbarHtml() {
    const cls = selectedClass();
    return `
      <div class="chrx-pending-toolbar">
        <input type="search" class="chrx-pending-search"
               placeholder="Search pending cards…"
               value="${esc(_state.filter)}">
        ${cls ? `<button type="button" class="chrx-pending-class-filter" data-clear-class-filter="1" title="Show all pending cards">${esc(cls.name || cls.id)} ×</button>` : ""}
        <div class="chrx-pending-groupby" role="tablist">
          ${Object.entries(GROUPS).map(([k, v]) =>
            `<button class="chrx-pending-tab ${_state.groupBy === k ? "active" : ""}" data-group="${k}">${esc(v.label)}</button>`
          ).join("")}
        </div>
      </div>
    `;
  }

  function groupHtml(g) {
    if (!g.cards.length) return "";
    // Stack same-lesson cards into piles: e.g. 3 Maths for V B = one pile with "×3" badge.
    const stacks = stackByLesson(g.cards);
    return `
      <div class="chrx-pending-group">
        <div class="chrx-pending-grouplabel">${esc(g.label)} <span class="chrx-pending-count">${g.cards.length}</span></div>
        <div class="chrx-pending-cards">
          ${stacks.map(s => stackHtml(s)).join("")}
        </div>
      </div>
    `;
  }

  /** Group an array of cards by lessonId, preserving order of first appearance. */
  function stackByLesson(cards) {
    const byLesson = Object.create(null);
    const order = [];
    for (const c of cards) {
      if (!byLesson[c.lessonId]) {
        byLesson[c.lessonId] = [];
        order.push(c.lessonId);
      }
      byLesson[c.lessonId].push(c);
    }
    return order.map(lid => byLesson[lid]);
  }

  /** Render a stack of same-lesson cards as a single pile with a count badge. */
  function stackHtml(cards) {
    const top = cards[0];
    const count = cards.length;
    const depth = Math.min(count - 1, 3); // visual stack depth caps at 3 shadow layers
    const stackClass = count > 1 ? " chrx-vk-stack" : "";
    const badge = count > 1 ? `<span class="chrx-vk-badge">×${count}</span>` : "";
    // Store all card IDs so the click handler can pick them off one by one.
    const allIds = cards.map(c => c.cardId).join(",");
    return `
      <div class="chrx-pending-item">
        <div class="chrx-vkarta chrx-vk-pending${stackClass}"
             data-card-id="${esc(top.cardId)}"
             data-lesson-id="${esc(top.lessonId)}"
             data-stack-ids="${esc(allIds)}"
             data-stack-depth="${depth}"
             style="--chrx-card-hue:${top.hue};--chrx-stack-depth:${depth}"
             title="${esc(top.title)}">
          <div class="chrx-vk-line1">${esc(top.subjShort)}</div>
          <div class="chrx-vk-line2">${esc(top.classShort)}</div>
          <div class="chrx-vk-line3">${esc(top.teacherShort)}</div>
          ${badge}
        </div>
        ${whyHtml(top.why)}
      </div>
    `;
  }

  /* ── "Why is this unplaced?" ───────────────────────────────────────────
   * Every pending card gets a one-line explanation built by sweeping the
   * card's OWN lesson over all candidate (day, period) slots and counting
   * how many slots each hard reason blocks. The per-slot verdict comes from
   * the existing classifier (window.Placement.classify) so the tray can
   * never disagree with the drag hover/commit guard.
   *
   * Two reasons the classifier does not model are added here rather than by
   * editing placement_validator.js: teacher/class daily caps (same
   * `maxPerDay` + globals fallback semantics as csp_solver's
   * TEACHER_MAX_PER_DAY / CLASS_MAX_PER_DAY) and card relations (the same
   * window.RelationEnforcer.check the constraint explainer uses). Both
   * degrade silently to "not reported" when their module has not loaded.
   */

  // Canonical reason buckets, in the order a planner wants to read them.
  const REASONS = [
    { key: "teacher",  label: "teacher busy" },
    { key: "class",    label: "class busy" },
    { key: "room",     label: "room busy" },
    { key: "timeoff",  label: "time-off" },
    { key: "dailycap", label: "daily cap" },
    { key: "relation", label: "relation" },
    { key: "roomtype", label: "room type" },
    { key: "bell",     label: "bell period" },
    { key: "fixed",    label: "fixed slot" },
    { key: "lab",      label: "needs P+1" },
  ];
  const REASON_INDEX = Object.create(null);
  REASONS.forEach((r, i) => { REASON_INDEX[r.key] = i; });

  /** Map a classify()/supplementary message onto a REASONS bucket. */
  function bucketOf(msg) {
    let m = String(msg == null ? "" : msg);
    // "lab P+1: class busy" is still a class conflict — fold it into the
    // class/teacher/room bucket so the tray does not report a second
    // "lab" reason for the same blocker.
    const lab = m.match(/^lab P\+1: (.*)$/);
    if (lab) m = lab[1];
    if (/^teacher .+ busy$/.test(m))   return "teacher";
    if (/^class .+ busy$/.test(m))     return "class";
    if (/^room .+ busy$/.test(m))      return "room";
    if (/^teacher .+ unavailable$/.test(m)) return "timeoff";
    if (/^room type .+ required$/.test(m)) return "roomtype";
    if (/bell has no period/.test(m))  return "bell";
    if (/^fixed /.test(m))             return "fixed";
    if (/^lab /.test(m))               return "lab";
    if (/^daily cap/.test(m))          return "dailycap";
    if (/^relation/.test(m))           return "relation";
    return null;
  }

  function candidateSlots(S) {
    const days = Math.max(1, Math.min(6, (S.daysPerWeek | 0) || 6));
    const periods = ((S.bell && S.bell.periods) || [])
      .filter(p => p && p.isTeaching !== false)
      .slice()
      .sort((a, b) => (a.index | 0) - (b.index | 0));
    const out = [];
    for (let d = 0; d < days; d++) for (const p of periods) out.push({ day: d, period: p.index | 0 });
    return out;
  }

  function slotIndex(S) {
    const map = new Map();
    for (const c of (S.cards || [])) {
      const k = (c.day | 0) + "_" + (c.period | 0);
      let arr = map.get(k);
      if (!arr) { arr = []; map.set(k, arr); }
      arr.push(c);
    }
    return map;
  }

  /** One pass over the placed cards → per-day teacher/class teaching counts. */
  function dayLoads(S, days) {
    const teacher = [], cls = [];
    for (let d = 0; d < days; d++) { teacher.push(Object.create(null)); cls.push(Object.create(null)); }
    for (const c of (S.cards || [])) {
      const d = c.day | 0;
      if (d < 0 || d >= days) continue;
      const L = S._idx && S._idx.lessonById ? S._idx.lessonById[c.lessonId] : null;
      if (!L) continue;
      for (const t of (L.teacherIds || [])) teacher[d][t] = (teacher[d][t] || 0) + 1;
      for (const k of (L.classIds || [])) cls[d][k] = (cls[d][k] || 0) + 1;
    }
    return { teacher, cls };
  }

  /** Mirrors csp_solver gFallback: per-entity value wins, then globals. */
  function capOf(entity, ownKey, globalKey, S) {
    const g = (S.globals && S.globals.constraints) || {};
    const own = entity ? entity[ownKey] : null;
    if (own != null && own !== "*" && own !== "i") return own | 0;
    const fb = g[globalKey];
    if (fb != null && fb !== "*" && fb !== "i") return fb | 0;
    return -1;
  }

  function capReasons(S, lesson, day, loads) {
    const out = [];
    for (const tid of (lesson.teacherIds || [])) {
      const t = S._idx.teacherById[tid];
      const cap = capOf(t, "maxPerDay", "teacherMaxPerDay", S);
      if (cap >= 0 && (loads.teacher[day][tid] || 0) >= cap) {
        out.push("daily cap (teacher " + ((t && (t.abbr || t.name)) || tid) + ")");
      }
    }
    for (const cid of (lesson.classIds || [])) {
      const c = S._idx.classById[cid];
      const cap = capOf(c, "maxPerDay", "classMaxPerDay", S);
      if (cap >= 0 && (loads.cls[day][cid] || 0) >= cap) {
        out.push("daily cap (class " + ((c && c.name) || cid) + ")");
      }
    }
    return out;
  }

  function relationReasons(S, lessonId, day, period) {
    const RE = window.RelationEnforcer;
    if (!RE || typeof RE.check !== "function") return [];
    try {
      const res = RE.check(S, lessonId, day, period);
      const hard = (res && res.hard) || [];
      return hard.length ? ["relation: " + hard[0]] : [];
    } catch (e) {
      return [];
    }
  }

  /** Per-slot sweep for one lesson → counts per reason bucket. */
  function explainLesson(S, lessonId) {
    const out = {
      total: 0, free: 0, amber: 0, blocked: 0,
      counts: Object.create(null), reasons: [], summary: "",
    };
    const lesson = S._idx && S._idx.lessonById ? S._idx.lessonById[lessonId] : null;
    const slots = candidateSlots(S);
    out.total = slots.length;
    if (!lesson || !slots.length) return out;
    const idx = slotIndex(S);
    const loads = dayLoads(S, Math.max(1, Math.min(6, (S.daysPerWeek | 0) || 6)));
    const classify = window.Placement && window.Placement.classify;

    for (const slot of slots) {
      let msgs = [];
      let red = false;
      if (classify) {
        const r = classify(lessonId, slot.day, slot.period, null,
          idx.get(slot.day + "_" + slot.period) || []);
        msgs = (r && r.reasons) || [];
        red = !!(r && r.validity === "red");
        if (!red && r && r.validity === "amber") out.amber++;
      }
      // Daily caps and relations are NOT modelled by placement_validator, so
      // they are always evaluated — a slot can be blocked by a class conflict
      // AND a daily cap at the same time, and both are worth reporting.
      const extra = capReasons(S, lesson, slot.day, loads)
        .concat(relationReasons(S, lessonId, slot.day, slot.period));
      if (extra.length) { msgs = msgs.concat(extra); red = true; }
      if (!red) { out.free++; continue; }
      out.blocked++;
      const seen = Object.create(null);
      for (const m of msgs) {
        const k = bucketOf(m);
        if (!k || seen[k]) continue;   // one slot counts once per bucket
        seen[k] = 1;
        out.counts[k] = (out.counts[k] || 0) + 1;
      }
    }

    out.reasons = REASONS
      .filter(r => out.counts[r.key] > 0)
      .map(r => ({ key: r.key, label: r.label, count: out.counts[r.key] }))
      .sort((a, b) => b.count - a.count || REASON_INDEX[a.key] - REASON_INDEX[b.key]);
    out.summary = whySummary(out);
    return out;
  }

  /** "No free slot: teacher busy in 31, class busy in 9" (top 3 reasons). */
  function whySummary(why) {
    if (!why || !why.total) return "";
    const top = why.reasons.slice(0, 3).map(r => r.label + " in " + r.count).join(", ");
    if (!why.free) return top ? "No free slot: " + top : "No free slot";
    const head = "Free in " + why.free + " of " + why.total;
    return top ? head + " · blocked: " + top : head;
  }

  function whyTitle(why) {
    if (!why || !why.total) return "";
    const all = why.reasons.map(r => r.label + ": " + r.count + " slots").join("\n");
    return why.free + " of " + why.total + " slots free" +
      (why.amber ? " (" + why.amber + " soft)" : "") +
      (all ? "\n" + all : "");
  }

  function whyHtml(why) {
    if (!why || !why.total) return "";
    const counts = why.reasons.map(r => r.label + ":" + r.count).join(",");
    return `
      <div class="chrx-pending-why ${why.free ? "is-free" : "is-blocked"}"
           data-why-free="${why.free}"
           data-why-blocked="${why.blocked}"
           data-why-reasons="${esc(counts)}">
        <span class="chrx-pending-why-text" title="${esc(whyTitle(why))}">${esc(why.summary)}</span>
        <button type="button" class="chrx-pending-why-link">Show in Verification</button>
      </div>
    `;
  }

  /* ── reason cache ──────────────────────────────────────────────────────
   * A search keystroke re-renders the whole tray; without this the 48-slot
   * sweep would re-run for every lesson on every keystroke. The signature
   * covers every input explainLesson reads, so a move/add/remove invalidates
   * it and nothing else does.
   */
  let _why = { sig: null, map: Object.create(null) };

  function gridSignature(S) {
    let s = (S.lessons || []).length + "#" + (S.relations || []).length + "#" + (S.daysPerWeek | 0) + "#";
    for (const c of (S.cards || [])) s += (c.lessonId || "") + (c.day | 0) + "." + (c.period | 0) + "|";
    return s;
  }

  function whyMapFor(S) {
    const sig = gridSignature(S);
    if (_why.sig !== sig) _why = { sig, map: Object.create(null) };
    return _why.map;
  }

  function whyFor(S, lessonId, cache) {
    if (!(lessonId in cache)) cache[lessonId] = explainLesson(S, lessonId);
    return cache[lessonId];
  }

  function wire(rootEl) {
    // Search + tab handlers are bound to elements created by innerHTML, so
    // they die with each re-render — no leak. But the rootEl-level
    // mousedown + the document-level editor:place subscription survive
    // every render and accumulated one listener per render. Gate them
    // wire-once via `_chrxWired`.
    rootEl.querySelector(".chrx-pending-search")?.addEventListener("input", (e) => {
      _state.filter = e.target.value.toLowerCase();
      render(rootEl);
    });
    rootEl.querySelectorAll(".chrx-pending-tab").forEach(btn => {
      btn.addEventListener("click", () => {
        _state.groupBy = btn.dataset.group || "subject";
        render(rootEl);
      });
    });
    rootEl.querySelector("[data-clear-class-filter]")?.addEventListener("click", () => {
      if (window.APP && window.APP.editor) window.APP.editor.selectedClassId = null;
      render(rootEl);
      const editor = document.querySelector(".chrx-editor");
      if (editor && window.Editor && window.Editor.render) window.Editor.render(editor);
    });
    // "Show in Verification" jumps to the existing Verification Pro panel
    // (never a second implementation of it — we only dispatch its event).
    rootEl.querySelectorAll(".chrx-pending-why-link").forEach(btn => {
      btn.addEventListener("click", (ev) => {
        ev.preventDefault();
        ev.stopPropagation();
        window.dispatchEvent(new CustomEvent("app:verification-pro"));
      });
    });
    rootEl.querySelector(".chrx-pending-resize")?.addEventListener("pointerdown", (ev) => {
      // Lane-curtain: once the curtain is mounted it owns vertical sizing,
      // because it OVERLAYS the grid and must stay the only thing that moves.
      // Letting the tray's legacy handle resize the tray independently would
      // give two drag paths the same gesture. The curtain's own handle is the
      // supported one; this forwards a stray grab of the old grip to it.
      if (curtainOwnsHeight() && window.Curtain.beginDrag) {
        ev.preventDefault();
        window.Curtain.beginDrag(ev);
        return;
      }
      startResize(ev, rootEl);
    });
    if (rootEl._chrxPendingWired) return;
    rootEl.addEventListener("mouseover", (ev) => {
      const vk = ev.target.closest(".chrx-vk-pending");
      if (!vk || !window.EditorCardInspector) return;
      window.EditorCardInspector.show(vk.dataset.lessonId, { source: "pending" });
    });
    rootEl.addEventListener("focusin", (ev) => {
      const vk = ev.target.closest(".chrx-vk-pending");
      if (!vk || !window.EditorCardInspector) return;
      window.EditorCardInspector.show(vk.dataset.lessonId, { source: "pending" });
    });
    rootEl.addEventListener("pointerdown", (ev) => {
      const vk = ev.target.closest(".chrx-vk-pending");
      if (!vk) return;
      if (ev.button !== 0) return;
      ev.preventDefault();
      
      const startX = ev.clientX;
      const startY = ev.clientY;
      const pointerId = ev.pointerId;
      const rect = vk.getBoundingClientRect();
      const grabRatioX = rect.width ? (startX - rect.left) / rect.width : 0.5;
      const grabRatioY = rect.height ? (startY - rect.top) / rect.height : 0.5;
      let dragTriggered = false;
      rootEl.setPointerCapture?.(pointerId);

      function onPointerMove(moveEv) {
        if (moveEv.pointerId !== pointerId) return;
        if (dragTriggered) return;
        const dx = moveEv.clientX - startX;
        const dy = moveEv.clientY - startY;
        if (Math.hypot(dx, dy) > 5) {
          dragTriggered = true;
          cleanup();
          startPendingDrag(vk, moveEv.clientX, moveEv.clientY, pointerId, grabRatioX, grabRatioY);
        }
      }

      function onPointerUp(upEv) {
        if (upEv.pointerId !== pointerId) return;
        cleanup();
        if (!dragTriggered && upEv.type !== "pointercancel") {
          handlePendingClick(vk);
        }
      }

      function cleanup() {
        rootEl.releasePointerCapture?.(pointerId);
        document.removeEventListener("pointermove", onPointerMove, true);
        document.removeEventListener("pointerup", onPointerUp, true);
        document.removeEventListener("pointercancel", onPointerUp, true);
      }

      document.addEventListener("pointermove", onPointerMove, true);
      document.addEventListener("pointerup", onPointerUp, true);
      document.addEventListener("pointercancel", onPointerUp, true);
    });
    document.addEventListener("editor:place", () => render(rootEl));
    rootEl._chrxPendingWired = true;
  }

  function startPendingDrag(vk, clientX, clientY, pointerId, grabRatioX, grabRatioY) {
    const cardId = vk.dataset.cardId, lessonId = vk.dataset.lessonId;
    window.APP.editor = window.APP.editor || {};
    window.APP.editor.cardInHand = { cardId, lessonId, fromPending: true, mode: "drag" };
    document.body.classList.add("chrx-card-in-hand");
    vk.classList.add("chrx-vk-taken");
    document.dispatchEvent(new CustomEvent("editor:pickup", { detail: {
      cardId, lessonId, fromPending: true, sourceX: clientX, sourceY: clientY,
      pointerId, grabRatioX, grabRatioY, mode: "drag"
    } }));
  }

  function handlePendingClick(vk) {
    const cardId = vk.dataset.cardId, lessonId = vk.dataset.lessonId;
    const held = window.APP.editor.cardInHand;
    if (held) {
      window.CardInHand.cancel();
      if (held.cardId === cardId) return;
    }
    
    window.APP.editor = window.APP.editor || {};
    window.APP.editor.cardInHand = { cardId, lessonId, fromPending: true, mode: "click" };
    document.body.classList.add("chrx-card-in-hand");
    
    document.dispatchEvent(new CustomEvent("editor:pickup", { detail: { cardId, lessonId, fromPending: true, mode: "click" } }));
    
    render(vk.closest(".chrx-pending-strip"));
  }

  function countPlaced(S) {
    const out = Object.create(null);
    for (const c of (S.cards || [])) out[c.lessonId] = (out[c.lessonId] || 0) + 1;
    
    const held = window.APP && window.APP.editor && window.APP.editor.cardInHand;
    if (held && held.lessonId) {
      out[held.lessonId] = (out[held.lessonId] || 0) + 1;
    }
    return out;
  }

  function buildGroups(S, placedCounts) {
    const groupKeyFn = GROUPS[_state.groupBy].keyFn;
    const f = (_state.filter || "").trim();
    const groups = Object.create(null);
    const classFilterId = window.APP && window.APP.editor && window.APP.editor.selectedClassId;
    const whyCache = whyMapFor(S);

   for (const L of (S.lessons || [])) {
     if (classFilterId && !(L.classIds || []).includes(classFilterId)) continue;
     const len = L.lessonLength || (L.isLabDouble ? 2 : 1);
     const ppw = Math.ceil(L.periodsPerWeek || 0);
     const needed = ppw > 0 ? Math.max(1, Math.round(ppw / len)) : 0;
     const placed = placedCounts[L.id] || 0;
     const missing = needed - placed;
     if (missing <= 0) continue;

      const subj = S._idx.subjectById[L.subjectId];
      const subjShort = subj ? (subj.abbr || subj.name) : "?";
      const teacherShort = (L.teacherIds || []).map(t=>S._idx.teacherById[t])
        .filter(Boolean).map(t=>t.abbr||t.name).join(", ");
      const classShort = (L.classIds || []).map(c=>S._idx.classById[c])
        .filter(Boolean).map(c=>c.name).join(", ");
      const title = `${subjShort} · ${classShort}${teacherShort ? ' · ' + teacherShort : ''} — ${missing} more`;
      const hue = pendingHue(S, L, subj);

      // Filter
      const hay = `${subjShort} ${classShort} ${teacherShort}`.toLowerCase();
      if (f && !hay.includes(f)) continue;

      // Why this card cannot be placed — computed once per lesson, not once
      // per card in the pile, and only for lessons that actually render.
      const why = whyFor(S, L.id, whyCache);

      const gKey = groupKeyFn(S, L) || "—";
      groups[gKey] = groups[gKey] || { label: gKey, cards: [] };

      for (let i = 0; i < missing; i++) {
        groups[gKey].cards.push({
          cardId: `pending_${L.id}_${i}`,
          lessonId: L.id,
          subjShort, teacherShort, classShort, title, hue, why,
        });
      }
    }
    return Object.values(groups).sort((a, b) => a.label.localeCompare(b.label));
  }

  function keyOf(rec) { return rec ? (rec.name || rec.abbr || "—") : "—"; }

  function selectedClass() {
    const S = window.APP && window.APP.school;
    const id = window.APP && window.APP.editor && window.APP.editor.selectedClassId;
    return S && S._idx && id ? S._idx.classById[id] : null;
  }

  /** True once the bottom curtain owns the tray's vertical sizing. */
  function curtainOwnsHeight() {
    return !!(window.Curtain && typeof window.Curtain.isMounted === "function"
      && window.Curtain.isMounted());
  }

  function applyTrayHeight(rootEl) {
    // Lane-curtain: the persisted height is an INLINE style, so no CSS rule
    // can override it — it has to be cleared here. Inside the curtain the
    // tray fills its slot instead (see css/lane-curtain.css §6).
    if (curtainOwnsHeight()) {
      rootEl.style.height = "";
      return;
    }
    const h = window.APP && window.APP.editor && window.APP.editor.pendingTrayHeight;
    if (Number.isFinite(h)) rootEl.style.height = Math.max(72, Math.min(420, h)) + "px";
  }

  function startResize(ev, rootEl) {
    ev.preventDefault();
    rootEl.setPointerCapture?.(ev.pointerId);
    const startY = ev.clientY;
    const startH = rootEl.getBoundingClientRect().height || 96;
    rootEl.classList.add("is-resizing");
    document.body.classList.add("chrx-body--resizing");
    function move(e) {
      const next = Math.max(72, Math.min(Math.round(window.innerHeight * 0.55), startH + (startY - e.clientY)));
      rootEl.style.height = next + "px";
      window.APP.editor = window.APP.editor || {};
      window.APP.editor.pendingTrayHeight = next;
    }
    function up(e) {
      rootEl.releasePointerCapture?.(ev.pointerId);
      rootEl.classList.remove("is-resizing");
      document.body.classList.remove("chrx-body--resizing");
      window.removeEventListener("pointermove", move, true);
      window.removeEventListener("pointerup", up, true);
    }
    window.addEventListener("pointermove", move, true);
    window.addEventListener("pointerup", up, true);
  }

  // Hue mirror — synced with grid_canvas.
  const SHORT_HUES = {
    MA:220,MAT:220,MATH:220,MATHS:220,EN:12,ENG:12,ENGL:12,HI:32,HIN:32,HINDI:32,
    SC:150,SCI:150,SCIE:150,SS:50,SST:50,SOC:50,MU:285,MUS:285,AR:330,ART:330,
    PE:110,PT:110,PED:110,SP:110,IT:250,CS:250,COMP:250,LIB:200,
  };
  function hueOf(s) {
    const k = (s || "").toUpperCase().replace(/[^A-Z]/g, "");
    if (SHORT_HUES[k] != null) return SHORT_HUES[k];
    let h = 0; for (let i = 0; i < k.length; i++) h = (h * 31 + k.charCodeAt(i)) & 0xffff;
    return h % 360;
  }

  function pendingHue(S, lesson, subject) {
    const axis = (window.APP && window.APP.editor && window.APP.editor.colorBy) || "subject";
    if (axis === "subject") return hueOf(subject ? (subject.abbr || subject.name) : "");
    if (axis === "teacher") {
      const tid = lesson.teacherIds && lesson.teacherIds[0];
      const t = tid ? S._idx.teacherById[tid] : null;
      return (t && hexHue(t.color)) ?? hashHue(t && (t.abbr || t.name || t.id));
    }
    if (axis === "class") {
      const cid = lesson.classIds && lesson.classIds[0];
      const c = cid ? S._idx.classById[cid] : null;
      return (c && hexHue(c.color)) ?? hashHue(c && (c.short || c.name || c.id));
    }
    if (axis === "room") {
      const r = lesson.preferredRoomId ? S._idx.classroomById[lesson.preferredRoomId] : null;
      return (r && hexHue(r.color)) ?? hashHue(r && (r.short || r.name || r.id));
    }
    return hueOf(subject ? (subject.abbr || subject.name) : "");
  }

  function hashHue(key) {
    if (!key) return 210;
    let h = 0;
    const u = String(key).toUpperCase();
    for (let i = 0; i < u.length; i++) h = (h * 31 + u.charCodeAt(i)) & 0xffff;
    return h % 360;
  }

  function hexHue(hex) {
    if (typeof hex !== "string") return null;
    const m = hex.replace("#", "");
    if (m.length !== 6) return null;
    const r = parseInt(m.slice(0, 2), 16) / 255;
    const g = parseInt(m.slice(2, 4), 16) / 255;
    const b = parseInt(m.slice(4, 6), 16) / 255;
    if ([r, g, b].some(v => Number.isNaN(v))) return null;
    const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min;
    if (d === 0) return 210;
    let h;
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
    return Math.round(h);
  }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g,
      c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c]));
  }

  return { render, explainLesson, whySummary, bucketOf };
})();

// [vite-esm] exports auto-generated by the 2026-07 Vite migration.
export const PendingStrip = window.PendingStrip;
