// [vite-esm] imports auto-generated by the 2026-07 Vite migration.
import "../../state.js";

/* Options — Settings, Constraints library, Preferences */
(function () {
  "use strict";
  const APP = window.APP;
  const fire = (n, d) => window.dispatchEvent(new CustomEvent(n, { detail: d || {} }));
  const has  = () => !!APP.school;

  APP.ribbon.registerMenu({
    key: "options", label: "Options",
    build() {
      return [
        { icon: "⚙︎", label: "School settings…",            disabled: !has(),
          run: () => fire("app:open-entity", { kind: "school" }) },
        { icon: "📜", label: "Constraints library…", disabled: !has(),
          run: () => fire("app:open-entity", { kind: "constraints" }) },
        { sep: true },
        { icon: "🖨", label: "Print defaults…",      disabled: !has(),
          run: () => fire("app:open-entity", { kind: "print-defaults" }) },
        { icon: "👮", label: "Supervision criteria…", disabled: !has(),
          run: () => fire("app:open-entity", { kind: "supervision-criteria" }) },
      ];
    },
  });
})();
